/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "../string_functions.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_function_stringtouint16_should_return_true_0_with_0(void);
extern void test_function_stringtouint16_should_return_true_29900_with_29900(void);
extern void test_function_stringtouint16_should_return_false_433_with_minus1(void);
extern void test_function_stringtouint16_should_return_true_65535_with_65535(void);
extern void test_function_stringtouint16_should_return_false_433_with_65536(void);
extern void test_function_stringtouint8_should_return_true_0_with_0(void);
extern void test_function_stringtouint8_should_return_true_99_with_99(void);
extern void test_function_stringtouint8_should_return_false_67_with_minus1(void);
extern void test_function_stringtouint8_should_return_true_255_with_255(void);
extern void test_function_stringtouint8_should_return_false_67_with_256(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test.c");
  run_test(test_function_stringtouint16_should_return_true_0_with_0, "test_function_stringtouint16_should_return_true_0_with_0", 14);
  run_test(test_function_stringtouint16_should_return_true_29900_with_29900, "test_function_stringtouint16_should_return_true_29900_with_29900", 19);
  run_test(test_function_stringtouint16_should_return_false_433_with_minus1, "test_function_stringtouint16_should_return_false_433_with_minus1", 24);
  run_test(test_function_stringtouint16_should_return_true_65535_with_65535, "test_function_stringtouint16_should_return_true_65535_with_65535", 29);
  run_test(test_function_stringtouint16_should_return_false_433_with_65536, "test_function_stringtouint16_should_return_false_433_with_65536", 34);
  run_test(test_function_stringtouint8_should_return_true_0_with_0, "test_function_stringtouint8_should_return_true_0_with_0", 41);
  run_test(test_function_stringtouint8_should_return_true_99_with_99, "test_function_stringtouint8_should_return_true_99_with_99", 46);
  run_test(test_function_stringtouint8_should_return_false_67_with_minus1, "test_function_stringtouint8_should_return_false_67_with_minus1", 51);
  run_test(test_function_stringtouint8_should_return_true_255_with_255, "test_function_stringtouint8_should_return_true_255_with_255", 56);
  run_test(test_function_stringtouint8_should_return_false_67_with_256, "test_function_stringtouint8_should_return_false_67_with_256", 61);

  return UnityEnd();
}
